# https://github.com/brigade/overcommit

PreCommit:
  BundleCheck:
    enabled: true

  EatYourDogfood:
    enabled: true
    custom_config_field: "You can totally do this..."

  KeepYourDogfoodFresh:
    enabled: true

  TrailingWhitespace:
    enabled: true
    problem_on_unmodified_line: ignore

CommitMsg:
  HardTabs:
    enabled: true

  RussianNovel:
    enabled: true

PrePush:
  PrintDiffUrls:
    enabled: true
    on_fail: warn
